### ISSUE TITLE
Install a  CustomResourceDefinition for datasets during development

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#223]
The basic idea is that we use Kubernetes [Custom Resources](https://kubernetes.io/docs/concepts/api-extension/custom-resources/) to store datasets in the kubernetes clusters. These dataset resources store metadata and are (a) reference(s) to were the actual data (blobs) lives. For now we only support our public-s3-sandbox-without-deduplication as a place for actual storage but in the future more can be supported. In terms of Metadata we would mostly want the size of a dataset to be stored but in the future one can image tags or up/down progress information to be available in dataset resources as well.

As an example the custom resource definition could look like this, take from [here](https://github.com/kubernetes/sample-controller/tree/master/artifacts/examples), also see: [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/):
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datasets.nerdalize.com
spec:
  group: nerdalize.com
  version: v1alpha1
  names:
    kind: Dataset
    plural: datasets
    shortNames:
    - ds
  scope: Namespaced
```

We would this definition to be available on the cluster we're developing for before we can begin.
